# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfigWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(463, 437)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.paratable = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paratable.sizePolicy().hasHeightForWidth())
        self.paratable.setSizePolicy(sizePolicy)
        self.paratable.setObjectName("paratable")
        self.paratable.setColumnCount(3)
        self.paratable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.paratable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.paratable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.paratable.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.paratable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(30, -1, 30, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.updateButton = QtWidgets.QPushButton(Form)
        self.updateButton.setMinimumSize(QtCore.QSize(0, 30))
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout.addWidget(self.updateButton)
        self.closeButton = QtWidgets.QPushButton(Form)
        self.closeButton.setMinimumSize(QtCore.QSize(0, 30))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "参数配置"))
        self.label.setText(_translate("Form", "双击单元格进行编辑"))
        item = self.paratable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "名称"))
        item = self.paratable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "路径/参数"))
        item = self.paratable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "备注"))
        self.updateButton.setText(_translate("Form", "更新"))
        self.closeButton.setText(_translate("Form", "关闭"))
